Repository infinum/eightshift-libs, pull requests merged in 2020-05, with the labels that each got.

#54 Add manifest json validation
  .travis.yml
  composer.json
  phpcs.xml.dist
  src/blocks/class-blocks.php
  src/class-main.php
  src/exception/class-component-exception.php
  src/exception/class-invalid-manifest.php
  src/has-activation-interface.php
  src/has-deactivation-interface.php
  src/helpers/class-components.php
  src/manifest/class-manifest.php
Labels: enhancement

#55 adding responsive-selector-helper
  CHANGELOG.md
  src/helpers/class-components.php
Labels: improvement

#56 Made the prepare method more flat
  CHANGELOG.md
  src/class-main.php
Labels: improvement

#58 Add GitHub actions
  .github/workflows/ci.yml
  bin/lintPhp.sh
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: improvement

#59 updating blocks
  CHANGELOG.md
  src/blocks/class-blocks.php
Labels: bug, improvement

#61 updating helper
  src/helpers/class-components.php
Labels: bug
