Repository infinum/eightshift-libs, pull requests merged in 2020-12, with the labels that each got.

#102 Trim before output
  src/Helpers/Components.php
Labels: bug

#103 Allowed more attributes on buttons
  src/View/AbstractEscapedView.php
Labels: bug

#107 Hotfix/manifest helper
  src/Cli/CliHelpers.php
  src/Columns/PostType/AbstractPostTypeColumns.php
  src/Config/ConfigCli.php
  src/Helpers/Components.php
  src/I18n/AbstractI18n.php
  src/I18n/I18nExample.php
  src/Login/AbstractLogin.php
  src/Login/LoginExample.php
  src/Media/AbstractMedia.php
  src/Media/MediaExample.php
  src/ModifyAdminAppearance/AbstractModifyAdminAppearance.php
  src/ModifyAdminAppearance/ModifyAdminAppearanceExample.php
Labels: bug, enhancement

#109 Rename BEM selector methods
  src/Helpers/Components.php
Labels: improvement

#114 Update Components.php
  src/Helpers/Components.php
Labels: bug, improvement

#120 Allow meta and link to be rendered with wp_kses_post
  src/View/AbstractEscapedView.php
Labels: improvement

#122 Update form allowed html list
  src/View/AbstractEscapedView.php
Labels: improvement

#116 Add additional svg path properties
  src/View/AbstractEscapedView.php
Labels: improvement
