Repository infinum/eightshift-libs, pull requests merged in 2020-03, with the labels that each got.

#46 Fixing enqueue classes for missing method
  CHANGELOG.md
  src/enqueue/class-assets.php
  src/enqueue/class-enqueue-admin.php
  src/enqueue/class-enqueue-blocks.php
  src/enqueue/class-enqueue-theme.php
Labels: urgent

#47 Fix the wrong text-domain
  src/custom-post-type/class-label-generator.php
Labels: bug

#49 Removed dependency from the enqueue classes
  CHANGELOG.md
  src/enqueue/class-enqueue-admin.php
  src/enqueue/class-enqueue-blocks.php
  src/enqueue/class-enqueue-theme.php
  src/manifest/class-manifest.php
Labels: enhancement
