Repository infinum/eightshift-libs, pull requests merged in 2021-04, with the labels that each got.

#174 Trigger checks on all PRs
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: bugfix, improvement

#172 Blocks Tests
  composer.json
  src/Blocks/AbstractBlocks.php
  src/Cli/AbstractCli.php
  tests/Blocks/BlockCliTest.php
  tests/Blocks/BlocksExampleTest.php
  tests/Helpers/ComponentHelpersTest.php
  tests/Media/MediaExampleTest.php
  tests/data/src/Blocks/custom/button/button-block.js
  tests/data/src/Blocks/custom/button/button-style.scss
  tests/data/src/Blocks/custom/button/button-transforms.js
  tests/data/src/Blocks/custom/button/button.php
  tests/data/src/Blocks/custom/button/components/button-editor.js
  tests/data/src/Blocks/custom/button/components/button-options.js
  tests/data/src/Blocks/custom/button/components/button-toolbar.js
  tests/data/src/Blocks/custom/button/docs/readme.mdx
  tests/data/src/Blocks/custom/button/docs/story.js
  tests/data/src/Blocks/custom/button/manifest.json
  tests/data/src/Blocks/manifest.json
  tests/data/src/Blocks/wrapper/manifest.json
  tests/data/src/Blocks/wrapper/wrapper.php
Labels: tests

#175 updating tests
  src/Blocks/AbstractBlocks.php
  tests/Blocks/BlocksExampleTest.php
  tests/Config/ConfigExampleTest.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/heading/manifest.json
  tests/data/src/Blocks/components/typography/manifest.json
  tests/data/src/Blocks/custom/heading/manifest.json
  tests/data/src/Blocks/wrapper/wrapper.php
Labels: tests

#178 updating helper for css variables
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/button/manifest.json
  tests/data/src/Blocks/components/typography/manifest.json
  tests/data/src/Blocks/custom/heading/manifest.json
Labels: improvement

#176 Tests - Helpers/Post
  src/Helpers/Post.php
  tests/Datasets/Arguments.php
  tests/Helpers/PostHelperTest.php
Labels: tests

#179 updating autowire to ignore main DI
  src/Main/Autowiring.php
Labels: bug, bugfix

#180 Update ConfigProjectExample.php
  src/ConfigProject/ConfigProjectExample.php
Labels: bugfix

#177 Feature/enqueue tests
  tests/Enqueue/Admin/EnqueueAdminExampleTest.php
  tests/Enqueue/Blocks/EnqueueBlockCliTest.php
  tests/Enqueue/Blocks/EnqueueBlockExampleTest.php
  tests/Enqueue/Theme/EnqueueThemeExampleTest.php
Labels: tests

#182 Fix faulty test
  tests/Blocks/BlocksExampleTest.php
Labels: bugfix, improvement

#185 Allow infinite number of levels in dependency tree
  src/Main/Autowiring.php
  tests/Datasets/Autowiring/Dependencies/ClassLvl1Dependency.php
  tests/Datasets/Autowiring/Dependencies/ClassLvl2Dependency.php
  tests/Datasets/Autowiring/Dependencies/ClassLvl3Dependency.php
  tests/Datasets/Autowiring/Dependencies/ClassLvl4Dependency.php
  tests/Datasets/Autowiring/Dependencies/ClassLvl5Dependency.php
  tests/Datasets/Autowiring/Dependencies/ClassLvl6Dependency.php
  tests/Datasets/Autowiring/Dependencies/ClassLvl7Dependency.php
  tests/Datasets/Autowiring/Services/ServiceWithDeepDependencyTree.php
  tests/Main/AutowiringTest.php
Labels: improvement

#184 Fixes incorrect folder detection when used in plugin
  src/Config/AbstractConfigData.php
Labels: bugfix

#187 updating variables helper
  src/Helpers/Components.php
  tests/Datasets/Arguments.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/typography/manifest.json
Labels: improvement

#188 updating new helper
  src/Cli/CliHelpers.php
  src/Db/ImportCli.php
  src/Helpers/Components.php
  src/Setup/UpdateCli.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/heading/manifest.json
  tests/data/src/Blocks/components/typography/manifest.json
Labels: improvement
