Repository infinum/eightshift-libs, pull requests merged in 2021-06, with the labels that each got.

#201 Fix props logic
  src/Helpers/Components.php
Labels: bugfix

#202 Props renaming fix
  src/Helpers/Components.php
Labels: improvement

#203 updating fixes to props
  src/Blocks/AbstractBlocks.php
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
Labels: bug, bugfix

#204 Responsive variables
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/responsiveVariables/manifest.json
Labels: improvement
