Repository infinum/eightshift-libs, pull requests merged in 2021-05, with the labels that each got.

#189 Feature/variables
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/typography/manifest.json
Labels: improvement

#190 updating responsive-select
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/typography/manifest.json
Labels: improvement

#191 Feature/variables
  src/Blocks/AbstractBlocks.php
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/variables/manifest.json
Labels: improvement

#192 updating variables
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/typography/manifest.json
  tests/data/src/Blocks/components/variables/manifest.json
Labels: improvement

#193 Fix correct boolean handling when outputting css variables
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
  tests/data/src/Blocks/components/variables/manifest.json
Labels: bug

#196 Kebab-case to camel case helper
  src/Cli/CliHelpers.php
  src/Helpers/Components.php
  tests/Cli/CliHelpersTest.php
  tests/Datasets/Arguments.php
  tests/Helpers/ComponentHelpersTest.php
Labels: improvement

#195 Minor setup fixes
  src/Blocks/BlocksCli.php
  src/Blocks/BlocksExample.php
  src/CustomPostType/PostTypeCli.php
  src/CustomPostType/PostTypeExample.php
  src/CustomTaxonomy/TaxonomyExample.php
Labels: bugfix

#194 Updates
  composer.json
  phpunit.xml
  src/Manifest/AbstractManifest.php
  tests/Blocks/BlocksExampleTest.php
  tests/Build/BuildCliTest.php
  tests/Enqueue/Admin/EnqueueAdminExampleTest.php
  tests/Enqueue/Blocks/EnqueueBlockExampleTest.php
  tests/Enqueue/Theme/EnqueueThemeExampleTest.php
  tests/Helpers.php
  tests/Main/AbstractMainTest.php
  tests/Manifest/ManifestExampleTest.php
  tests/Menu/MenuExampleTest.php
  tests/data/src/FirstMockServiceClass.php
  tests/data/src/SecondMockServiceClass.php
Labels: improvement, tests

#197 Change github plugin install path
  src/Setup/Setup.php
Labels: improvement

#163 Abstract pattern class
  src/BlockPatterns/AbstractBlockPattern.php
  src/BlockPatterns/BlockPatternCli.php
  src/BlockPatterns/BlockPatternExample.php
  src/Blocks/BlocksCli.php
  src/Cli/CliHelpers.php
  tests/BlockPatterns/BlockPatternCliTest.php
  tests/BlockPatterns/BlockPatternExampleTest.php
  tests/Blocks/BlockCliTest.php
  tests/Blocks/BlocksCliTest.php
  tests/Datasets/Arguments.php
Labels: feature request

#199 Remove readme command from the setup theme script
  src/Cli/CliInitTheme.php
Labels: bugfix, improvement

#198 Register BlockPattern CLI command
  src/BlockPatterns/BlockPatternExample.php
  src/Cli/Cli.php
  tests/Cli/CliTest.php
Labels: improvement

#200 Fix plugin install for GitHub plugins
  src/Cli/CliHelpers.php
  src/Setup/Setup.php
  src/Setup/setup.json
  tests/Cli/CliHelpersTest.php
  tests/Datasets/Arguments.php
  tests/Setup/UpdateCliTest.php
Labels: bugfix
