Repository infinum/eightshift-libs, pull requests merged in 2021-01, with the labels that each got.

#128 updating language priority
  src/I18n/I18nExample.php
Labels: bug

#131 updating env handler
  src/Config/AbstractConfigData.php
  src/Config/ConfigCli.php
  src/Config/ConfigDataInterface.php
  src/Config/ConfigExample.php
  src/ConfigProject/ConfigProjectCli.php
  src/ConfigProject/ConfigProjectExample.php
  src/ModifyAdminAppearance/ModifyAdminAppearanceExample.php
Labels: bug

#129 Fix global varible name for Shortcode class
  src/Helpers/Shortcode.php
Labels: bugfix

#125 Improve array processing in AbstractBlocks
  src/Blocks/AbstractBlocks.php
Labels: enhancement

#132 Add codeowners file
  .github/CODEOWNERS
Labels: enhancement

#136 Fix all the phpstan violations
  src/Blocks/BlockComponentCli.php
  src/Blocks/BlockVariationCli.php
  src/Cli/AbstractCli.php
  src/CustomTaxonomy/TaxonomyCli.php
Labels: bugfix, improvement

#137 updating readme
  src/Cli/CliInitProject.php
  src/Cli/CliInitTheme.php
  src/Readme/README-project.md
  src/Readme/README.md
  src/Readme/ReadmeCli.php
Labels: improvement

#138 Update AbstractBlocks.php
  src/Blocks/AbstractBlocks.php
Labels: bugfix
