Repository infinum/eightshift-libs, pull requests merged in 2021-07, with the labels that each got.

#211 updating block registration and helpers for new props prefixes
  src/Blocks/AbstractBlocks.php
  src/Blocks/BlocksExample.php
  src/Exception/InvalidBlock.php
  src/Helpers/Components.php
Labels: bugfix, improvement

#216 Fix ci checks
  src/Blocks/AbstractBlocks.php
  src/Helpers/Post.php
  tests/Helpers/PostHelperTest.php
Labels: bugfix

#217 Fix for responsive variables mobile first
  src/Helpers/Components.php
Labels: bugfix, improvement

#218 Set only variables custom
  src/Helpers/Components.php
Labels: bugfix, improvement

#215 Add admin menus cli
  .gitattributes
  src/AdminMenus/AbstractAdminMenu.php
  src/AdminMenus/AbstractAdminSubMenu.php
  src/AdminMenus/AdminMenuCli.php
  src/AdminMenus/AdminMenuExample.php
  src/AdminMenus/AdminSubMenuCli.php
  src/AdminMenus/AdminSubMenuExample.php
  src/CustomPostType/PostTypeCli.php
  tests/AdminMenus/AdminMenuCliTest.php
  tests/AdminMenus/AdminMenuExampleTest.php
  tests/AdminMenus/AdminSubMenuCliTest.php
Labels: improvement

#221 Fix for default breakpoints
  src/Helpers/Components.php
  tests/Helpers/ComponentHelpersTest.php
Labels: bugfix, improvement

#222 Default breakpoints -- docs fix
  src/Helpers/Components.php
Labels: improvement

#220 Feature/all blocks
  src/Blocks/AbstractBlocksCli.php
  src/Blocks/BlockCli.php
  src/Blocks/BlockComponentCli.php
  src/Cli/CliInitTheme.php
Labels: improvement

#224 Additional phpstan fixes
  composer.json
  src/AdminMenus/AdminMenuCli.php
  src/Helpers/Components.php
  tests/AdminMenus/AdminMenuCliTest.php
Labels: bugfix, improvement

#225 adding fix for title typo
  src/AdminMenus/AdminSubMenuCli.php
Labels: bugfix

#228 Fix check attr phpstan issues
  src/Helpers/Components.php
Labels: bugfix
