Repository infinum/eightshift-libs, pull requests merged in 2022-06, with the labels that each got.

#296 Geolocation service class
  src/Cli/Cli.php
  src/Geolocation/AbstractGeolocation.php
  src/Geolocation/GeolocationCli.php
  src/Geolocation/GeolocationExample.php
  src/Geolocation/Readme.md
  src/Geolocation/manifest.json
  tests/Cli/CliTest.php
Labels: improvement

#299 Adding variations to store
  src/Blocks/AbstractBlocks.php
  src/Exception/InvalidBlock.php
  src/Helpers/StoreTrait.php
Labels: improvement, feature request

#252 Feature/gdpr settings
  src/AnalyticsGdpr/AnalyticsGdprCli.php
  src/AnalyticsGdpr/AnalyticsGdprExample.php
  src/Cli/Cli.php
  src/Cli/CliInitTheme.php
  src/Menu/BemMenuWalker.php
  tests/AnalyticsGdpr/AnalyticsGdprCliTest.php
  tests/AnalyticsGdpr/AnalyticsGdprExampleTest.php
  tests/Blocks/BlocksExampleTest.php
  tests/Cli/CliTest.php
  tests/Helpers.php
  tests/ThemeOptions/ThemeOptionsCliTest.php
  tests/ThemeOptions/ThemeOptionsExampleTest.php
Labels: improvement, wpcli

#297 WIP: adding loadmore route
  src/Cli/Cli.php
  src/Rest/Routes/LoadMore/LoadMoreRouteCli.php
  src/Rest/Routes/LoadMore/LoadMoreRouteExample.php
Labels: improvement

#304 Add lock false to composer json config
  composer.json
Labels: improvement
