Repository infinum/eightshift-libs, pull requests merged in 2022-07, with the labels that each got.

#316 Boolean logic allowed blocks -- fix allowed_block_types_all filter callback
  src/Blocks/AbstractBlocks.php
  tests/Datasets/Arguments.php
  tests/Unit/Blocks/BlocksExampleTest.php
Labels: improvement, bugfix

#282 Rename method arguments that are using reserved keywords
  src/Cli/AbstractCli.php
  src/Columns/Taxonomy/AbstractTaxonomyColumns.php
  src/Helpers/ObjectHelperTrait.php
  src/Main/AbstractMain.php
  src/Main/Autowiring.php
  src/Menu/AbstractMenu.php
  src/Rest/CallableFieldInterface.php
  src/Rest/Fields/FieldExample.php
  tests/Helpers.php
  tests/Unit/Columns/TaxonomyColumnsTest.php
Labels: PHP8

#319 Return empty string in tests in getAssetsManifestItem
  .github/workflows/test.yml
  src/Manifest/AbstractManifest.php
  tests/Unit/Columns/TaxonomyColumnsTest.php
  tests/Unit/Manifest/ManifestExampleTest.php
Labels: bugfix, tests
