Repository infinum/eightshift-libs, pull requests merged in 2022-05, with the labels that each got.

#286 Change test variable
  phpunit.xml
  src/Blocks/AbstractBlocks.php
  src/Blocks/AbstractBlocksCli.php
  src/Blocks/BlockVariationCli.php
  src/Blocks/BlockWrapperCli.php
  src/Cli/AbstractCli.php
  src/Cli/CliInitAll.php
  src/Cli/CliInitProject.php
  src/Cli/CliInitTheme.php
  src/Helpers/Components.php
  src/Manifest/AbstractManifest.php
  src/Setup/UpdateCli.php
  tests/Cli/AbstractCliTest.php
Labels: improvement, bugfix

#272 Improve developer experience on Windows
  src/Blocks/AbstractBlocksCli.php
  src/Blocks/BlocksCli.php
  src/Cli/AbstractCli.php
  src/Cli/CliInitAll.php
  src/Helpers/Components.php
  src/Helpers/CssVariablesTrait.php
Labels: bugfix, windows

#294 Fix the check that should allow only custom blocks to be added
  src/Blocks/AbstractBlocks.php
Labels: bugfix

#295 Add captainHook package
  captainhook.json
  composer.json
  package.json
Labels: improvement
