Repository infinum/eightshift-libs, pull requests merged in 2024-11, with the labels that each got.

#437 Fix fetching of ids for partials of provided templates
  src/InitSetup/tailwind/theme/404.php
  src/InitSetup/tailwind/theme/footer.php
  src/InitSetup/tailwind/theme/header.php
  src/ThemeOptions/ThemeOptionsExample.php
Labels: bug

#440 Cache Autowiring::buildServiceClasses into a transient
  src/Cache/AbstractManifestCache.php
  src/InitSetup/standard/plugin/eightshift-boilerplate-plugin.php
  src/InitSetup/standard/theme/functions.php
  src/InitSetup/tailwind/plugin/eightshift-boilerplate-plugin.php
  src/InitSetup/tailwind/theme/functions.php
  src/Main/Autowiring.php
Labels: improvement

#438 Better CLI loading for ServiceInterface implementations
  src/ClassAttributes/ShouldLoadInCliContext.php
  src/Main/AbstractMain.php
Labels: improvement, wpcli
